### ISSUE TITLE
Can't get token value outside of FCMPlugin.getToken()

### ISSUE THREAD

**Issue by sreerajkarippala** [fechanique/cordova-plugin-fcm#172]
i am using ionic 2 and i tried example code, work fine and alert push token. but when i try to return token value outside of FCMPlugin.getToken() it gives `undefined`. this is my code:
`        
        var token = FCMPlugin.getToken(
            function(token) {
                return token;
            }
        );
        alert(token);
`  

thank you.....

**Comment by MarcoGiesen** [comment]
The problem is that you are  excepting a promise to return immediately. The code is executed asynchronously at that point, so this won't work. You can easily evaluate this, if you use two alerts -> one outside and one inside the getToken. The outside one will probably be called first. 

You got two options here:

1. Wait for the promise to finish -> you can use Observables in Ionic2
2. Do whatever you wanted to do in the getToken function

**Comment by sreerajkarippala** [comment]
yes i got it

**Comment by feliperoan** [comment]
Hello to both, I have a great doubt regarding the operation of FCMplugin, it works since the notifications arrive but I would like to know how I handle those functions, at least I am working with ionic 2 and I would like to be able to obtain the token of First time in my class.TS Or my component to send it to a server, the token is printed in console but how can I get it in my class?

**Comment by MarcoGiesen** [comment]
Hello @fechanique 
I don't really understand your problem, could you provide me with some additional information?

What I understand so far is;
- You have one component which generates the Token
- You want to send this specific token to your Server, this requests is handled in a different class/object (whatever)? or do you simple want it to store somewhere and send it to the server later?

You have some option (Just a guess what you want to do):
1. In the promise return of getToken make an additional call to your components which handles the comminication to your backend server. In this request you send the freshly generated token. 
2. Wrap your promise call in a new function, which stores the token somewhere (local database, session..). This new function should be observable (if you use ionic2) or a promise you can use to detect if the token is generated. 

The first solution is simpler and implemented very fast. The second solution is kind of more dynamic and allows wrap the requests a bit for more logic (like storing local tokens and check if it changed before sending it to the server etc.). If you have any more question maybe you can give me some sample code so we can narrow down your problem. 

Best regards
Marco
