### ISSUE TITLE
Conflict with abmobpro

### ISSUE THREAD

**Issue by etherny** [fechanique/cordova-plugin-fcm#214]
Hello, i have an error during build, when admobpro is activated, the build crash with a google services 9.0.0 error.
I had the same error with < 2.0.0 version but resolved with a gcm in 9.2.0 version.
But this solution do not work in > 2.0.0

Thank you.

Look like this error : 
```
Found com.google.android.gms:play-services-gcm:+, but version 9.0.0 is needed for the google-services plugin.
```

**Comment by punksta** [comment]
The problem is: ```android.gms:play-services-ads``` is a part of firebase now:https://firebase.google.com/docs/admob/admob-firebase

You can't have both in project.
Solution is changing `android.gms:play-services-ads` to `com.google.firebase:firebase-ads` if you use firebase. I created fork of `cordova-admob-pro` plugin to demonstrate it. https://github.com/punksta/cordova-admob-pro/commit/aa64fa36895aabcc3c67282497c37adf9e5aed86

**Comment by etherny** [comment]
I will try this, come back to you in few mins

**Comment by dalejomen** [comment]
good morning,
I have problems with the plugin cordova-plugin-admobpro when I compile my project and generate the apk for android generates it well. but when I install the apk in my cellphone to application does not load the program is closed.

This was working fine until last week as this plugin used it in several apps.

**Comment by nocodedweb** [comment]
@punksta thank you!  this is the only solution that worked for me.
