### ISSUE TITLE
Ionic framework compatible?

### ISSUE THREAD

**Issue by filimongeorge** [fechanique/cordova-plugin-fcm#8]
Can this plugin be used with the Ionic framework? Has anyone ever tried that?

**Comment by rodrigo-fonseca** [comment]
Ionic is build on top of Cordova, so yes, you can use Ionic with it.

**Comment by majodi** [comment]
It would help a lot if there was somewhat more info or example for Ionic (2). My personal goal is to get Push Notification going on Ionic 2 / Angular 2. I filtered out this plugin because I use Firebase (3) and the Ionic platform messaging is still far from ready. I understand that there are many details (on the platform side, like certificates, profiles, etc.) but a basic typescript Ionic example/tutorial (with typings covered, Cordova install covered, etc.) to get a minimal running setup with the current Ionic beta 2 would be great...
